// <auto-generated />
using System;
using E7BeautyShop.AgendaService.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E7BeautyShop.Appointment.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240611054023_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.DayRest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOnWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("DaysRest");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.OfficeHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndHour")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("OfficeHours");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.Catalog", b =>
                {
                    b.OwnsOne("E7BeautyShop.AgendaService.Domain.ServiceDescription", "ServiceDescription", b1 =>
                        {
                            b1.Property<Guid>("CatalogId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Description_Name");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Description_Price");

                            b1.HasKey("CatalogId");

                            b1.ToTable("Catalogs");

                            b1.WithOwner()
                                .HasForeignKey("CatalogId");
                        });

                    b.Navigation("ServiceDescription");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.DayRest", b =>
                {
                    b.HasOne("E7BeautyShop.AgendaService.Domain.Schedule", null)
                        .WithMany("DaysRest")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.OfficeHour", b =>
                {
                    b.HasOne("E7BeautyShop.AgendaService.Domain.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId");

                    b.HasOne("E7BeautyShop.AgendaService.Domain.Schedule", null)
                        .WithMany("OfficeHours")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("E7BeautyShop.AgendaService.Domain.CustomerId", "CustomerId", b1 =>
                        {
                            b1.Property<Guid>("OfficeHourId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Customer_Id");

                            b1.HasKey("OfficeHourId");

                            b1.ToTable("OfficeHours");

                            b1.WithOwner()
                                .HasForeignKey("OfficeHourId");
                        });

                    b.Navigation("Catalog");

                    b.Navigation("CustomerId");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.Schedule", b =>
                {
                    b.OwnsOne("E7BeautyShop.AgendaService.Domain.ProfessionalId", "ProfessionalId", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Professional_Id");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("E7BeautyShop.AgendaService.Domain.Weekday", "Weekday", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("EndAt")
                                .HasColumnType("time")
                                .HasColumnName("Weekday_EndAt");

                            b1.Property<TimeSpan>("StartAt")
                                .HasColumnType("time")
                                .HasColumnName("Weekday_StartAt");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("E7BeautyShop.AgendaService.Domain.Weekend", "Weekend", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("EndAt")
                                .HasColumnType("time")
                                .HasColumnName("Weekend_EndAt");

                            b1.Property<TimeSpan>("StartAt")
                                .HasColumnType("time")
                                .HasColumnName("Weekend_StartAt");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("ProfessionalId");

                    b.Navigation("Weekday");

                    b.Navigation("Weekend");
                });

            modelBuilder.Entity("E7BeautyShop.AgendaService.Domain.Schedule", b =>
                {
                    b.Navigation("DaysRest");

                    b.Navigation("OfficeHours");
                });
#pragma warning restore 612, 618
        }
    }
}
